export enum ErrorCode {
  // System & Common (1000 - 1999)
  INTERNAL_SERVER_ERROR = 'SYS_1000_INTERNAL_ERROR',
  VALIDATION_FAILED = 'SYS_1001_VALIDATION_FAILED',
  BAD_REQUEST = 'SYS_1002_BAD_REQUEST',
  RESOURCE_NOT_FOUND = 'SYS_1003_NOT_FOUND',
  TOO_MANY_REQUESTS = 'SYS_1004_TOO_MANY_REQUESTS',
  SERVICE_UNAVAILABLE = 'SYS_1005_SERVICE_UNAVAILABLE',

  // Authentication & Security (2000 - 2999)
  AUTH_INVALID_CREDENTIALS = 'AUTH_2000_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_2001_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_2002_TOKEN_INVALID',
  AUTH_UNAUTHORIZED = 'AUTH_2003_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_2004_FORBIDDEN',
  AUTH_ACCOUNT_LOCKED = 'AUTH_2005_ACCOUNT_LOCKED',

  // User Management (3000 - 3999)
  USER_NOT_FOUND = 'USER_3000_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_3001_ALREADY_EXISTS',
  USER_QUOTA_EXCEEDED = 'USER_3002_QUOTA_EXCEEDED',
  USER_INACTIVE = 'USER_3003_INACTIVE',

  // File Management (4000 - 4999)
  FILE_NOT_FOUND = 'FILE_4000_NOT_FOUND',
  FILE_ALREADY_EXISTS = 'FILE_4001_ALREADY_EXISTS',
  FILE_TOO_LARGE = 'FILE_4002_TOO_LARGE',
  FILE_INVALID_TYPE = 'FILE_4003_INVALID_TYPE',
  FILE_LOCKED = 'FILE_4004_LOCKED',
  FILE_CORRUPTED = 'FILE_4005_CORRUPTED',

  // Folder Management (5000 - 5999)
  FOLDER_NOT_FOUND = 'FOLDER_5000_NOT_FOUND',
  FOLDER_ALREADY_EXISTS = 'FOLDER_5001_ALREADY_EXISTS',
  FOLDER_NOT_EMPTY = 'FOLDER_5002_NOT_EMPTY',
  FOLDER_CIRCULAR_DEPENDENCY = 'FOLDER_5003_CIRCULAR_DEPENDENCY',

  // Storage Providers (Cloud / Local) (6000 - 6999)
  STORAGE_UPLOAD_FAILED = 'STORAGE_6000_UPLOAD_FAILED',
  STORAGE_DOWNLOAD_FAILED = 'STORAGE_6001_DOWNLOAD_FAILED',
  STORAGE_DELETE_FAILED = 'STORAGE_6002_DELETE_FAILED',
  STORAGE_PROVIDER_UNAVAILABLE = 'STORAGE_6003_PROVIDER_UNAVAILABLE',
  STORAGE_PRESIGNED_URL_FAILED = 'STORAGE_6004_PRESIGNED_URL_FAILED',

  // Sharing & Permissions (7000 - 7999)
  SHARING_PERMISSION_DENIED = 'SHARE_7000_PERMISSION_DENIED',
  SHARING_LINK_EXPIRED = 'SHARE_7001_LINK_EXPIRED',
  SHARING_LINK_NOT_FOUND = 'SHARE_7002_LINK_NOT_FOUND',
  SHARING_INVALID_PASSWORD = 'SHARE_7003_INVALID_PASSWORD',

  // Trash & Recovery (8000 - 8999)
  TRASH_ITEM_IN_TRASH = 'TRASH_8000_ITEM_IN_TRASH',
  TRASH_ITEM_NOT_IN_TRASH = 'TRASH_8001_ITEM_NOT_IN_TRASH',
  TRASH_RESTORE_FAILED = 'TRASH_8002_RESTORE_FAILED',
  TRASH_PERMANENT_DELETE_FAILED = 'TRASH_8003_PERMANENT_DELETE_FAILED',

  // Version Control (9000 - 9999)
  VERSION_NOT_FOUND = 'VER_9000_NOT_FOUND',
  VERSION_LIMIT_EXCEEDED = 'VER_9001_LIMIT_EXCEEDED',
  VERSION_RESTORE_FAILED = 'VER_9002_RESTORE_FAILED',
}
